#name: Github push
#on:
#  push:
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#      with:
#        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
#        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
#    #- name: Create local changes
#      # run: |
#        # touch MAHAAHAH.js
#        # echo "MAHAHAHAH" >> MAHAAHAH.js
#    - name: Commit files
#      run: |
#        git config --local user.email "a1amaya@ucsd.edu"
#        git config --local user.name "ArturoAmaya"
#        git add --all
#        git commit -m "Add changes" -a
#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        branch: ${{ github.ref }}
