name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
#    needs: [jestTest, jestCoverage, cypressTest]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - run: echo Complete.
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
    - run: npm -v
#     - run: npm install
#     - run: node test.js
#     - run: npm install --save-dev jest babel-jest @babel/core @babel/preset-env puppeteer jest-puppeteer
#     - run: npm run build --if-present
  
#  jestTest:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: npm run jest_test
#      - run: echo Jest Test complete.
  
#  jestCoverage:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: npm run jest_coverage
#      - run: echo Jest Coverage complete.
  
#  cypressTest:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: npm run cypress_test
#      - run: echo Cypress Test complete.
